default: 
  adapter: postgresql
  encoding: unicode
  host: "<%= ENV['POSTGRES_HOST'] %>"
  password: "<%= ENV['POSTGRES_PASSWORD'] %>"
  pool: 5
  timeout: 5000
  username: "<%= ENV['POSTGRES_USER'] %>"
development: 
  adapter: postgresql
  database: "<%= ENV['POSTGRES_DB'] %>"
  encoding: unicode
  host: "<%= ENV['POSTGRES_HOST'] %>"
  password: "<%= ENV['POSTGRES_PASSWORD'] %>"
  pool: 5
  timeout: 5000
  username: "<%= ENV['POSTGRES_USER'] %>"
production: 
  adapter: postgresql
  database: "<%= ENV['POSTGRES_DB'] %>"
  encoding: unicode
  host: "<%= ENV['POSTGRES_HOST'] %>"
  password: "<%= ENV['POSTGRES_PASSWORD'] %>"
  pool: 5
  timeout: 5000
  username: "<%= ENV['POSTGRES_USER'] %>"
test: 
  adapter: postgresql
  database: "<%= ENV['POSTGRES_TEST_DB'] %>"
  encoding: unicode
  host: "<%= ENV['POSTGRES_HOST'] %>"
  password: "<%= ENV['POSTGRES_PASSWORD'] %>"
  pool: 5
  timeout: 5000
  username: "<%= ENV['POSTGRES_USER'] %>"